plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
baseurl: /gemini

title: Memory Machine
description: A Machine that owns Memory.
